using AutoMapper;
using CertificateManagerAPI.DTO;
using CertificateManagerAPI.Entities;

namespace CertificateManagerAPI.Mappers
{
    public class CommentProfile : Profile
    {
        public CommentProfile()
        {
            // Mapping from entity to DTO
            CreateMap<Comment, CommentDTO>()
                .ForMember(dest => dest.Username,
                    opt => opt.MapFrom(src => src.User.Username));

            // Mapping from DTO to entity
            CreateMap<CommentDTO, Comment>()
                .ForMember(dest => dest.CommentId,
                    opt => opt.Ignore()) // Ignore CommentId as it's generated by the database
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.User,
                    opt => opt.Ignore()); // Ignore User navigation property
        }
    }
}
